const SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL';
const SIGNUP_UNSUCCESSFUL = 'SIGNUP_UNSUCCESSFUL';
const SIGNUP_VALIDATION_USER_ERROR = 'SIGNUP_VALIDATION_USER_ERROR';
const SIGNUP_VALIDATION_EMAIL_ERROR = 'SIGNUP_VALIDATION_EMAIL_ERROR';

const SIGNIN_SUCCESSFUL = 'SIGNIN_SUCCESSFUL';
const SIGNIN_UNSUCCESSFUL = 'SIGNIN_UNSUCCESSFUL';

const LOGOUT_USER = 'LOGOUT_USER';
const FETCH_RECIPES = 'FETCH_RECIPES';
const FETCH_SAMPLE_RECIPES = 'FETCH_SAMPLE_RECIPES';

export default {
  LOGOUT_USER,
  SIGNIN_SUCCESSFUL,
  SIGNUP_SUCCESSFUL,
  SIGNUP_UNSUCCESSFUL,
  SIGNIN_UNSUCCESSFUL,
  SIGNUP_VALIDATION_USER_ERROR,
  SIGNUP_VALIDATION_EMAIL_ERROR,
  FETCH_RECIPES,
  FETCH_SAMPLE_RECIPES
}