const SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL';
const SIGNUP_UNSUCCESSFUL = 'SIGNUP_UNSUCCESSFUL';
const SIGNUP_VALIDATION_USER_ERROR = 'SIGNUP_VALIDATION_USER_ERROR';
const SIGNUP_VALIDATION_EMAIL_ERROR = 'SIGNUP_VALIDATION_EMAIL_ERROR';

const SIGNIN_SUCCESSFUL = 'SIGNIN_SUCCESSFUL';
const SIGNIN_UNSUCCESSFUL = 'SIGNIN_UNSUCCESSFUL';

export default {
  SIGNIN_SUCCESSFUL,
  SIGNUP_SUCCESSFUL,
  SIGNUP_UNSUCCESSFUL,
  SIGNIN_UNSUCCESSFUL,
  SIGNUP_VALIDATION_USER_ERROR,
  SIGNUP_VALIDATION_EMAIL_ERROR
}