/* jshint esversion: 6 */
const SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL';
const SIGNUP_UNSUCCESSFUL = 'SIGNUP_UNSUCCESSFUL';
const SIGNUP_VALIDATION_USER_ERROR = 'SIGNUP_VALIDATION_USER_ERROR';
const SIGNUP_VALIDATION_EMAIL_ERROR = 'SIGNUP_VALIDATION_EMAIL_ERROR';

const SIGNIN_SUCCESSFUL = 'SIGNIN_SUCCESSFUL';
const SIGNIN_UNSUCCESSFUL = 'SIGNIN_UNSUCCESSFUL';

const LOGOUT_USER = 'LOGOUT_USER';
const FETCH_RECIPES = 'FETCH_RECIPES';
const FETCH_SINGLE_RECIPE = 'FETCH_SINGLE_RECIPE';
const FETCH_SAMPLE_RECIPES = 'FETCH_SAMPLE_RECIPES';
const CREATE_POST = 'CREATE_POST';
const SESSION_EXPIRED = 'SESSION_EXPIRED';
const SELECTED_ROUTE = 'SELECTED_ROUTE';
const UPVOTE_POST = 'UPVOTE_POST';
const DOWNVOTE_POST = 'DOWNVOTE_POST';

export default {
  LOGOUT_USER,
  SIGNIN_SUCCESSFUL,
  SIGNUP_SUCCESSFUL,
  SIGNUP_UNSUCCESSFUL,
  SIGNIN_UNSUCCESSFUL,
  SIGNUP_VALIDATION_USER_ERROR,
  SIGNUP_VALIDATION_EMAIL_ERROR,
  FETCH_RECIPES,
  FETCH_SINGLE_RECIPE,
  FETCH_SAMPLE_RECIPES,
  CREATE_POST,
  SESSION_EXPIRED,
  SELECTED_ROUTE,
  UPVOTE_POST,
  DOWNVOTE_POST
};
